/* tslint:disable */
/* eslint-disable */
/**
 * Collins API
 * This site provides details on the various ways that you can integrate with Collins. Not sure you want to be here after all? Check out what’s new on the [London Bar Scene](https://www.designmynight.com/london/new-bar-spy) instead. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ViewAssignedArea,
    ViewAssignedAreaFromJSON,
    ViewAssignedAreaFromJSONTyped,
    ViewAssignedAreaToJSON,
} from './';

/**
 * 
 * @export
 * @interface BookingAssignedAreasResponse
 */
export interface BookingAssignedAreasResponse {
    /**
     * An array of the areas which this booking is assigned to.
     * @type {Array<ViewAssignedArea>}
     * @memberof BookingAssignedAreasResponse
     */
    assignedAreas?: Array<ViewAssignedArea>;
}

export function BookingAssignedAreasResponseFromJSON(json: any): BookingAssignedAreasResponse {
    return BookingAssignedAreasResponseFromJSONTyped(json, false);
}

export function BookingAssignedAreasResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingAssignedAreasResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'assignedAreas': !exists(json, 'assigned_areas') ? undefined : ((json['assigned_areas'] as Array<any>).map(ViewAssignedAreaFromJSON)),
    };
}

export function BookingAssignedAreasResponseToJSON(value?: BookingAssignedAreasResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'assigned_areas': value.assignedAreas === undefined ? undefined : ((value.assignedAreas as Array<any>).map(ViewAssignedAreaToJSON)),
    };
}


