/* tslint:disable */
/* eslint-disable */
/**
 * Collins API
 * This site provides details on the various ways that you can integrate with Collins. Not sure you want to be here after all? Check out what’s new on the [London Bar Scene](https://www.designmynight.com/london/new-bar-spy) instead. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ViewCustomer,
    ViewCustomerFromJSON,
    ViewCustomerFromJSONTyped,
    ViewCustomerToJSON,
} from './';

/**
 * 
 * @export
 * @interface CustomerListResponse
 */
export interface CustomerListResponse {
    /**
     * 
     * @type {Array<ViewCustomer>}
     * @memberof CustomerListResponse
     */
    customers?: Array<ViewCustomer>;
}

export function CustomerListResponseFromJSON(json: any): CustomerListResponse {
    return CustomerListResponseFromJSONTyped(json, false);
}

export function CustomerListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerListResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'customers': !exists(json, 'customers') ? undefined : ((json['customers'] as Array<any>).map(ViewCustomerFromJSON)),
    };
}

export function CustomerListResponseToJSON(value?: CustomerListResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'customers': value.customers === undefined ? undefined : ((value.customers as Array<any>).map(ViewCustomerToJSON)),
    };
}


