/* tslint:disable */
/* eslint-disable */
/**
 * Collins API
 * This site provides details on the various ways that you can integrate with Collins. Not sure you want to be here after all? Check out what’s new on the [London Bar Scene](https://www.designmynight.com/london/new-bar-spy) instead. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse429
 */
export interface InlineResponse429 {
    /**
     * A description of the error
     * @type {string}
     * @memberof InlineResponse429
     */
    message?: string;
}

export function InlineResponse429FromJSON(json: any): InlineResponse429 {
    return InlineResponse429FromJSONTyped(json, false);
}

export function InlineResponse429FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse429 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function InlineResponse429ToJSON(value?: InlineResponse429 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}


