/* tslint:disable */
/* eslint-disable */
/**
 * Collins API
 * This site provides details on the various ways that you can integrate with Collins. Not sure you want to be here after all? Check out what’s new on the [London Bar Scene](https://www.designmynight.com/london/new-bar-spy) instead. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MoneyResponse
 */
export interface MoneyResponse {
    /**
     * The currency which this is in, in ISO-4217 format.
     * @type {string}
     * @memberof MoneyResponse
     */
    currency?: string;
    /**
     * The amount in pence.
     * @type {string}
     * @memberof MoneyResponse
     */
    amount?: string;
}

export function MoneyResponseFromJSON(json: any): MoneyResponse {
    return MoneyResponseFromJSONTyped(json, false);
}

export function MoneyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MoneyResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'currency': !exists(json, 'currency') ? undefined : json['currency'],
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
    };
}

export function MoneyResponseToJSON(value?: MoneyResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'currency': value.currency,
        'amount': value.amount,
    };
}


