/* tslint:disable */
/* eslint-disable */
/**
 * Collins API
 * This site provides details on the various ways that you can integrate with Collins. Not sure you want to be here after all? Check out what’s new on the [London Bar Scene](https://www.designmynight.com/london/new-bar-spy) instead. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The address of the customer's company
 * @export
 * @interface NewCustomerRequestCompanyAddress
 */
export interface NewCustomerRequestCompanyAddress {
    /**
     * The street name of the customer's company
     * @type {object}
     * @memberof NewCustomerRequestCompanyAddress
     */
    street?: object;
    /**
     * The city of the customer's company
     * @type {object}
     * @memberof NewCustomerRequestCompanyAddress
     */
    city?: object;
    /**
     * The post code of the customer's company
     * @type {object}
     * @memberof NewCustomerRequestCompanyAddress
     */
    postCode?: object;
}

export function NewCustomerRequestCompanyAddressFromJSON(json: any): NewCustomerRequestCompanyAddress {
    return NewCustomerRequestCompanyAddressFromJSONTyped(json, false);
}

export function NewCustomerRequestCompanyAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewCustomerRequestCompanyAddress {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'street': !exists(json, 'street') ? undefined : json['street'],
        'city': !exists(json, 'city') ? undefined : json['city'],
        'postCode': !exists(json, 'post_code') ? undefined : json['post_code'],
    };
}

export function NewCustomerRequestCompanyAddressToJSON(value?: NewCustomerRequestCompanyAddress | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'street': value.street,
        'city': value.city,
        'post_code': value.postCode,
    };
}


