/* tslint:disable */
/* eslint-disable */
/**
 * Collins API
 * This site provides details on the various ways that you can integrate with Collins. Not sure you want to be here after all? Check out what’s new on the [London Bar Scene](https://www.designmynight.com/london/new-bar-spy) instead. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    NewCustomerRequestCompanyAddress,
    NewCustomerRequestCompanyAddressFromJSON,
    NewCustomerRequestCompanyAddressFromJSONTyped,
    NewCustomerRequestCompanyAddressToJSON,
} from './';

/**
 * 
 * @export
 * @interface NewCustomerRequest
 */
export interface NewCustomerRequest {
    /**
     * The customer's email address
     * @type {string}
     * @memberof NewCustomerRequest
     */
    email?: string;
    /**
     * The customer's first name
     * @type {string}
     * @memberof NewCustomerRequest
     */
    firstName?: string;
    /**
     * The customer's last name
     * @type {string}
     * @memberof NewCustomerRequest
     */
    lastName?: string;
    /**
     * The customer's phone number
     * @type {string}
     * @memberof NewCustomerRequest
     */
    phone?: string;
    /**
     * The name of the customer's company
     * @type {string}
     * @memberof NewCustomerRequest
     */
    company?: string;
    /**
     * 
     * @type {NewCustomerRequestCompanyAddress}
     * @memberof NewCustomerRequest
     */
    companyAddress?: NewCustomerRequestCompanyAddress;
    /**
     * The customer's date of birth in the YYYY-MM-DD format
     * @type {Date}
     * @memberof NewCustomerRequest
     */
    dob?: Date;
    /**
     * The value given for the custom field
     * @type {object}
     * @memberof NewCustomerRequest
     */
    customFieldValue?: object;
    /**
     * An array of venue IDs this customer should be associated with
     * @type {Array<string>}
     * @memberof NewCustomerRequest
     */
    associatedVenues?: Array<string>;
    /**
     * An array of marketing preference IDs which the user should be opted in to.
     * @type {Array<string>}
     * @memberof NewCustomerRequest
     */
    marketingPreferenceIds?: Array<string>;
    /**
     * An object of marketing preference IDs as the key, and whether or not the user should be opted in or out of as the value.
     * @type {object}
     * @memberof NewCustomerRequest
     */
    marketingPreferences?: object;
    /**
     * An array of labels which should be set on the customer
     * @type {Array<string>}
     * @memberof NewCustomerRequest
     */
    labels?: Array<string>;
    /**
     * Any additional notes to make about the customer
     * @type {string}
     * @memberof NewCustomerRequest
     */
    notes?: string;
}

export function NewCustomerRequestFromJSON(json: any): NewCustomerRequest {
    return NewCustomerRequestFromJSONTyped(json, false);
}

export function NewCustomerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewCustomerRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
        'firstName': !exists(json, 'first_name') ? undefined : json['first_name'],
        'lastName': !exists(json, 'last_name') ? undefined : json['last_name'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'company': !exists(json, 'company') ? undefined : json['company'],
        'companyAddress': !exists(json, 'company_address') ? undefined : NewCustomerRequestCompanyAddressFromJSON(json['company_address']),
        'dob': !exists(json, 'dob') ? undefined : (new Date(json['dob'])),
        'customFieldValue': !exists(json, 'custom_field_value') ? undefined : json['custom_field_value'],
        'associatedVenues': !exists(json, 'associated_venues') ? undefined : json['associated_venues'],
        'marketingPreferenceIds': !exists(json, 'marketing_preference_ids') ? undefined : json['marketing_preference_ids'],
        'marketingPreferences': !exists(json, 'marketing_preferences') ? undefined : json['marketing_preferences'],
        'labels': !exists(json, 'labels') ? undefined : json['labels'],
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
    };
}

export function NewCustomerRequestToJSON(value?: NewCustomerRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'first_name': value.firstName,
        'last_name': value.lastName,
        'phone': value.phone,
        'company': value.company,
        'company_address': NewCustomerRequestCompanyAddressToJSON(value.companyAddress),
        'dob': value.dob === undefined ? undefined : (value.dob.toISOString().substr(0,10)),
        'custom_field_value': value.customFieldValue,
        'associated_venues': value.associatedVenues,
        'marketing_preference_ids': value.marketingPreferenceIds,
        'marketing_preferences': value.marketingPreferences,
        'labels': value.labels,
        'notes': value.notes,
    };
}


