/* tslint:disable */
/* eslint-disable */
/**
 * Collins API
 * This site provides details on the various ways that you can integrate with Collins. Not sure you want to be here after all? Check out what’s new on the [London Bar Scene](https://www.designmynight.com/london/new-bar-spy) instead. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ViewNotification,
    ViewNotificationFromJSON,
    ViewNotificationFromJSONTyped,
    ViewNotificationToJSON,
} from './';

/**
 * 
 * @export
 * @interface NotificationResponse
 */
export interface NotificationResponse {
    /**
     * 
     * @type {ViewNotification}
     * @memberof NotificationResponse
     */
    notification?: ViewNotification;
}

export function NotificationResponseFromJSON(json: any): NotificationResponse {
    return NotificationResponseFromJSONTyped(json, false);
}

export function NotificationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'notification': !exists(json, 'notification') ? undefined : ViewNotificationFromJSON(json['notification']),
    };
}

export function NotificationResponseToJSON(value?: NotificationResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'notification': ViewNotificationToJSON(value.notification),
    };
}


