/* tslint:disable */
/* eslint-disable */
/**
 * Collins API
 * This site provides details on the various ways that you can integrate with Collins. Not sure you want to be here after all? Check out what’s new on the [London Bar Scene](https://www.designmynight.com/london/new-bar-spy) instead. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ViewNotification,
    ViewNotificationFromJSON,
    ViewNotificationFromJSONTyped,
    ViewNotificationToJSON,
} from './';

/**
 * 
 * @export
 * @interface NotificationsListResponse
 */
export interface NotificationsListResponse {
    /**
     * 
     * @type {Array<ViewNotification>}
     * @memberof NotificationsListResponse
     */
    notifications?: Array<ViewNotification>;
}

export function NotificationsListResponseFromJSON(json: any): NotificationsListResponse {
    return NotificationsListResponseFromJSONTyped(json, false);
}

export function NotificationsListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationsListResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'notifications': !exists(json, 'notifications') ? undefined : ((json['notifications'] as Array<any>).map(ViewNotificationFromJSON)),
    };
}

export function NotificationsListResponseToJSON(value?: NotificationsListResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'notifications': value.notifications === undefined ? undefined : ((value.notifications as Array<any>).map(ViewNotificationToJSON)),
    };
}


