/* tslint:disable */
/* eslint-disable */
/**
 * Collins API
 * This site provides details on the various ways that you can integrate with Collins. Not sure you want to be here after all? Check out what’s new on the [London Bar Scene](https://www.designmynight.com/london/new-bar-spy) instead. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ViewVenue,
    ViewVenueFromJSON,
    ViewVenueFromJSONTyped,
    ViewVenueToJSON,
} from './';

/**
 * 
 * @export
 * @interface VenueResponse
 */
export interface VenueResponse {
    /**
     * 
     * @type {ViewVenue}
     * @memberof VenueResponse
     */
    venue?: ViewVenue;
}

export function VenueResponseFromJSON(json: any): VenueResponse {
    return VenueResponseFromJSONTyped(json, false);
}

export function VenueResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VenueResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'venue': !exists(json, 'venue') ? undefined : ViewVenueFromJSON(json['venue']),
    };
}

export function VenueResponseToJSON(value?: VenueResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'venue': ViewVenueToJSON(value.venue),
    };
}


