/* tslint:disable */
/* eslint-disable */
/**
 * Collins API
 * This site provides details on the various ways that you can integrate with Collins. Not sure you want to be here after all? Check out what’s new on the [London Bar Scene](https://www.designmynight.com/london/new-bar-spy) instead. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViewBookingAssignedAreas
 */
export interface ViewBookingAssignedAreas {
    /**
     * The ID of the area.
     * @type {object}
     * @memberof ViewBookingAssignedAreas
     */
    id?: object;
    /**
     * The name of the area.
     * @type {object}
     * @memberof ViewBookingAssignedAreas
     */
    name?: object;
    /**
     * The ID of the zone this area belongs to.
     * @type {object}
     * @memberof ViewBookingAssignedAreas
     */
    zone?: object | null;
}

export function ViewBookingAssignedAreasFromJSON(json: any): ViewBookingAssignedAreas {
    return ViewBookingAssignedAreasFromJSONTyped(json, false);
}

export function ViewBookingAssignedAreasFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewBookingAssignedAreas {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'zone': !exists(json, 'zone') ? undefined : json['zone'],
    };
}

export function ViewBookingAssignedAreasToJSON(value?: ViewBookingAssignedAreas | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'zone': value.zone,
    };
}


