/* tslint:disable */
/* eslint-disable */
/**
 * Collins API
 * This site provides details on the various ways that you can integrate with Collins. Not sure you want to be here after all? Check out what’s new on the [London Bar Scene](https://www.designmynight.com/london/new-bar-spy) instead. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViewAssignedArea
 */
export interface ViewAssignedArea {
    /**
     * The ID of the area.
     * @type {string}
     * @memberof ViewAssignedArea
     */
    id?: string;
    /**
     * The name of the area.
     * @type {string}
     * @memberof ViewAssignedArea
     */
    name?: string;
    /**
     * The ID of the zone which this area belongs to, or `null` if it doesn't belong to a zone.
     * @type {string}
     * @memberof ViewAssignedArea
     */
    zone?: string | null;
}

export function ViewAssignedAreaFromJSON(json: any): ViewAssignedArea {
    return ViewAssignedAreaFromJSONTyped(json, false);
}

export function ViewAssignedAreaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewAssignedArea {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'zone': !exists(json, 'zone') ? undefined : json['zone'],
    };
}

export function ViewAssignedAreaToJSON(value?: ViewAssignedArea | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'zone': value.zone,
    };
}


