/* tslint:disable */
/* eslint-disable */
/**
 * Collins API
 * This site provides details on the various ways that you can integrate with Collins. Not sure you want to be here after all? Check out what’s new on the [London Bar Scene](https://www.designmynight.com/london/new-bar-spy) instead. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViewCustomerMarketingPreferences
 */
export interface ViewCustomerMarketingPreferences {
    /**
     * The ID of the marketing preference
     * @type {string}
     * @memberof ViewCustomerMarketingPreferences
     */
    id?: string;
    /**
     * The date the customer last opted into this preference
     * @type {Date}
     * @memberof ViewCustomerMarketingPreferences
     */
    optInDate?: Date;
    /**
     * The date the customer last opted out of this preference
     * @type {Date}
     * @memberof ViewCustomerMarketingPreferences
     */
    optOutDate?: Date;
    /**
     * Whether or not the customer is currently opted into this preference
     * @type {boolean}
     * @memberof ViewCustomerMarketingPreferences
     */
    optedIn?: boolean;
}

export function ViewCustomerMarketingPreferencesFromJSON(json: any): ViewCustomerMarketingPreferences {
    return ViewCustomerMarketingPreferencesFromJSONTyped(json, false);
}

export function ViewCustomerMarketingPreferencesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewCustomerMarketingPreferences {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'optInDate': !exists(json, 'opt_in_date') ? undefined : (new Date(json['opt_in_date'])),
        'optOutDate': !exists(json, 'opt_out_date') ? undefined : (new Date(json['opt_out_date'])),
        'optedIn': !exists(json, 'opted_in') ? undefined : json['opted_in'],
    };
}

export function ViewCustomerMarketingPreferencesToJSON(value?: ViewCustomerMarketingPreferences | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'opt_in_date': value.optInDate === undefined ? undefined : (value.optInDate.toISOString()),
        'opt_out_date': value.optOutDate === undefined ? undefined : (value.optOutDate.toISOString()),
        'opted_in': value.optedIn,
    };
}


