/* tslint:disable */
/* eslint-disable */
/**
 * Collins API
 * This site provides details on the various ways that you can integrate with Collins. Not sure you want to be here after all? Check out what’s new on the [London Bar Scene](https://www.designmynight.com/london/new-bar-spy) instead. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The address of the venue.
 * @export
 * @interface ViewVenueAddress
 */
export interface ViewVenueAddress {
    /**
     * 
     * @type {string}
     * @memberof ViewVenueAddress
     */
    buildingName?: string;
    /**
     * 
     * @type {string}
     * @memberof ViewVenueAddress
     */
    street?: string;
    /**
     * 
     * @type {string}
     * @memberof ViewVenueAddress
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof ViewVenueAddress
     */
    postcode?: string;
}

export function ViewVenueAddressFromJSON(json: any): ViewVenueAddress {
    return ViewVenueAddressFromJSONTyped(json, false);
}

export function ViewVenueAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewVenueAddress {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'buildingName': !exists(json, 'building_name') ? undefined : json['building_name'],
        'street': !exists(json, 'street') ? undefined : json['street'],
        'city': !exists(json, 'city') ? undefined : json['city'],
        'postcode': !exists(json, 'postcode') ? undefined : json['postcode'],
    };
}

export function ViewVenueAddressToJSON(value?: ViewVenueAddress | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'building_name': value.buildingName,
        'street': value.street,
        'city': value.city,
        'postcode': value.postcode,
    };
}


